---
apiVersion: v1
kind: Namespace
metadata:
   name: pmo-core
   labels:
      mesh: appmesh-core
      appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
   name: appmesh-core
spec:
   namespaceSelector:
      matchLabels:
         mesh: appmesh-core